#harmo (koalascope user)
AWS_S3_HOST: harmondsworth.aee.bt.co.uk
AWS_S3_PORT: 8773
AWS_S3_VIRTUAL_PATH: /services/Walrus
AWS_CALLING_FORMAT: REGULAR
HTTP_PROXY_HOST: proxy.intra.bt.com
HTTP_PROXY_PORT: 8080

