package com.bt.pi.integration.util;

import java.util.ArrayList;
import java.util.List;

import com.bt.pi.core.cli.commands.CommandExecutionException;
import com.bt.pi.core.testing.StubCommandRunner;
import com.bt.pi.core.util.common.CommandResult;

public class StubIntegrationCommandRunner extends StubCommandRunner {
    private int delaySeconds;
    private boolean failure;

    public void setDelaySeconds(int value) {
        delaySeconds = value;
    }

    public void setFailure(boolean failure) {
        this.failure = failure;
    }

    @Override
    public CommandResult run(String commandLine) {
        if (commandLine.startsWith("iptables-save")) {
            return new CommandResult(0, sampleIptablesOutput(), new ArrayList<String>());
        } else if (commandLine.startsWith("nice -n +10 ionice -c3 cp var/volumes/remote")) {
            if (failure) {
                super.run(commandLine);
                throw new CommandExecutionException();
            }

            try {
                Thread.sleep(delaySeconds * 1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        return super.run(commandLine);
    }

    private List<String> sampleIptablesOutput() {
        List<String> sb = new ArrayList<String>();
        sb.add("*nat");
        sb.add(":PREROUTING ACCEPT [0:0]");
        sb.add(":POSTROUTING ACCEPT [2:120]");
        sb.add(":OUTPUT ACCEPT [2:120]");
        sb.add(":POST-9W0ioE23GzlYxZDnfEkrFw== - [0:0]");
        sb.add(":POST-hgvHy68+HHdL/uFREcfE1Q== - [0:0]");
        sb.add(":POST-sOPwadtSCBogG/2OYDBM0w== - [0:0]");
        sb.add(":bb - [0:0]");
        sb.add("-A PREROUTING -d 1.2.3.4/32 -j DNAT --to-destination 172.0.0.2 ");
        sb.add("-A PREROUTING -d 5.6.7.8/32 -j DNAT --to-destination 172.0.0.18");
        sb.add("-A PREROUTING -d 9.10.11.12/32 -j DNAT --to-destination 172.0.0.45");
        sb.add("-A POSTROUTING -d 172.0.0.32/28 -j POST-hgvHy68+HHdL/uFREcfE1Q==");
        sb.add("-A POSTROUTING -d 172.0.0.16/28 -j POST-9W0ioE23GzlYxZDnfEkrFw==");
        sb.add("-A POSTROUTING -d 172.0.0.0/28 -j POST-sOPwadtSCBogG/2OYDBM0w==");
        sb.add("-A OUTPUT -d 1.2.3.4/32 -j DNAT --to-destination 172.0.0.2");
        sb.add("-A OUTPUT -d 5.6.7.8/32 -j DNAT --to-destination 172.0.0.18");
        sb.add("-A OUTPUT -d 9.10.11.12/32 -j DNAT --to-destination 172.0.0.45");
        sb.add("-A POST-9W0ioE23GzlYxZDnfEkrFw== -d 172.0.0.18/32 -j SNAT --to-source 5.6.7.8");
        sb.add("-A POST-hgvHy68+HHdL/uFREcfE1Q== -d 172.0.0.45/32 -j SNAT --to-source 9.10.11.12");
        sb.add("-A POST-sOPwadtSCBogG/2OYDBM0w== -d 172.0.0.2/32 -j SNAT --to-source 1.2.3.4");
        sb.add("COMMIT");
        sb.add("# Completed on Fri Oct 16 09:48:48 2009");
        sb.add("# Generated by iptables-save v1.4.1.1 on Fri Oct 16 09:48:48 2009");
        sb.add("*filter");
        sb.add(":INPUT ACCEPT [212801:217224757]");
        sb.add(":FORWARD ACCEPT [0:0]");
        sb.add(":OUTPUT ACCEPT [148444:25148602]");
        sb.add(":FLTR-9W0ioE23GzlYxZDnfEkrFw== - [0:0]");
        sb.add(":FLTR-hgvHy68+HHdL/uFREcfE1Q== - [0:0]");
        sb.add(":FLTR-sOPwadtSCBogG/2OYDBM0w== - [0:0]");
        sb.add(":aa+aa - [0:0]");
        sb.add(":aa/aa - [0:0]");
        sb.add(":aa_aa - [0:0]");
        sb.add(":pi-chain - [0:0]");
        sb.add("-A FORWARD -j pi-chain");
        sb.add("-A FLTR-9W0ioE23GzlYxZDnfEkrFw== -s 1.2.3.4/32 -d 172.0.0.16/28 -p udp -j ACCEPT");
        sb.add("-A FLTR-sOPwadtSCBogG/2OYDBM0w== -d 172.0.0.0/28 -p tcp -m tcp --dport 22 -j ACCEPT");
        sb.add("-A pi-chain -d 172.0.0.0/28 -j FLTR-sOPwadtSCBogG/2OYDBM0w==");
        sb.add("-A pi-chain -d 172.0.0.16/28 -j FLTR-9W0ioE23GzlYxZDnfEkrFw==");
        sb.add("-A pi-chain -d 172.0.0.32/28 -j FLTR-hgvHy68+HHdL/uFREcfE1Q==");
        sb.add("COMMIT");
        sb.add("# Completed on Fri Oct 16 09:48:48 2009");
        return sb;
    }
}
